/*
 * keyboard_conf.h
 *
 *  Created on: Oct 29, 2023
 *      Author: xq123
 */

#ifndef KEYBOARD_CONF_H_
#define KEYBOARD_CONF_H_

//#define EXTENDED_SAMPLING

//#define PAUSE_TIM_WHEN_CALCULATING

#define DEFAULT_ADVANCED_KEY_MODE LEFL_KEY_ANALOG_RAPID_MODE

#define DEFAULT_TRIGGER_DISTANCE 0.05

#define DEFAULT_RELEASE_DISTANCE 0.05

#define DEFAULT_UPPER_DEADZONE 0.02

#define DEFAULT_LOWER_DEADZONE 0.10

#endif /* KEYBOARD_CONF_H_ */
